# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "8ae5da528e7f163ed3ffbe5e84b20711"
application_url = "https://ann-matched-ci-accomplished.trycloudflare.com"
embedded = true
name = "demo"
handle = "demo-1677"

[build]
automatically_update_urls_on_dev = true
include_config_on_deploy = true

[webhooks]
api_version = "2025-01"

  [[webhooks.subscriptions]]
  topics = [ "products/update" ]
  uri = "/app/question3"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_customers,read_orders,read_products,write_products"

[auth]
redirect_urls = [
  "https://ann-matched-ci-accomplished.trycloudflare.com/auth/callback",
  "https://ann-matched-ci-accomplished.trycloudflare.com/auth/shopify/callback",
  "https://ann-matched-ci-accomplished.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false
